# Generated by Django 5.2.7 on 2026-06-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(max_length=80, verbose_name='Petit label')),
                ('title_before', models.CharField(max_length=140, verbose_name='Titre principal')),
                ('title_accent', models.CharField(max_length=90, verbose_name='Titre accentué')),
                ('subtitle', models.TextField(verbose_name='Description courte')),
                ('primary_label', models.CharField(max_length=60, verbose_name='Bouton principal')),
                ('primary_url', models.CharField(max_length=220, verbose_name='Lien bouton principal')),
                ('secondary_label', models.CharField(blank=True, max_length=60, verbose_name='Bouton secondaire')),
                ('secondary_url', models.CharField(blank=True, max_length=220, verbose_name='Lien bouton secondaire')),
                ('background_image', models.ImageField(blank=True, help_text='Format recommandé : 1920 x 900 px, WebP ou JPG, moins de 350 Ko.', null=True, upload_to='home/slides/', verbose_name='Image de fond')),
                ('theme', models.CharField(choices=[('gold', 'Or - Immigration97'), ('blue', 'Bleu - Études'), ('green', 'Vert - Résidence'), ('purple', 'Violet - IA'), ('orange', 'Orange - Ressources')], default='gold', max_length=20, verbose_name='Style visuel')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Ordre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide accueil',
                'verbose_name_plural': 'Slides accueil',
                'ordering': ['order', 'id'],
            },
        ),
    ]
