# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0002_default_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitercontact",
            name="country",
            field=models.CharField(
                choices=[
                    ("CA", "Canada"),
                    ("NZ", "Nouvelle-Zélande"),
                    ("FR", "France"),
                    ("DE", "Allemagne"),
                    ("BE", "Belgique"),
                    ("CH", "Suisse"),
                    ("AU", "Australie"),
                    ("GB", "Royaume-Uni"),
                    ("US", "États-Unis"),
                    ("MA", "Maroc"),
                    ("SN", "Sénégal"),
                    ("CI", "Côte d'Ivoire"),
                    ("OTHER", "Autre"),
                ],
                db_index=True,
                default="CA",
                max_length=10,
                verbose_name="Pays",
            ),
        ),
        migrations.CreateModel(
            name="ScrapedEmployerLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=240, verbose_name="Titre / poste")),
                ("company_name", models.CharField(blank=True, max_length=220, verbose_name="Employeur")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("CA", "Canada"),
                            ("NZ", "Nouvelle-Zélande"),
                            ("AU", "Australie"),
                            ("EU", "Europe"),
                            ("FR", "France"),
                            ("DE", "Allemagne"),
                            ("BE", "Belgique"),
                            ("CH", "Suisse"),
                            ("GB", "Royaume-Uni"),
                            ("IE", "Irlande"),
                            ("NL", "Pays-Bas"),
                            ("IT", "Italie"),
                            ("ES", "Espagne"),
                            ("PT", "Portugal"),
                            ("OTHER", "Autre"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Pays cible",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture / Agroalimentaire"),
                            ("construction", "Construction / BTP"),
                            ("tech", "Technologie / IT"),
                            ("sante", "Santé / Médical"),
                            ("logistique", "Transport / Logistique"),
                            ("hotellerie", "Hôtellerie / Restauration"),
                            ("education", "Éducation / Formation"),
                            ("finance", "Finance / Comptabilité"),
                            ("industrie", "Industrie / Manufacture"),
                            ("commerce", "Commerce / Vente"),
                            ("services", "Services aux entreprises"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        default="autre",
                        max_length=30,
                        verbose_name="Secteur",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=180, verbose_name="Localisation")),
                ("job_url", models.URLField(max_length=600, unique=True, verbose_name="URL offre / preuve")),
                ("source_url", models.URLField(blank=True, max_length=600, verbose_name="URL source")),
                ("website", models.URLField(blank=True, max_length=400, verbose_name="Site employeur")),
                ("contact_email", models.EmailField(blank=True, max_length=254, verbose_name="Email détecté")),
                ("visa_signal", models.CharField(blank=True, max_length=180, verbose_name="Signal visa")),
                ("evidence_text", models.TextField(blank=True, verbose_name="Extrait de preuve")),
                ("confidence_score", models.PositiveSmallIntegerField(default=0, verbose_name="Score confiance")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("reviewed", "Vérifié"),
                            ("imported", "Importé"),
                            ("rejected", "Rejeté"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict, verbose_name="Données brutes")),
                ("first_seen_at", models.DateTimeField(auto_now_add=True, verbose_name="Première détection")),
                ("last_seen_at", models.DateTimeField(auto_now=True, verbose_name="Dernière détection")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead employeur scrapé",
                "verbose_name_plural": "Leads employeurs scrapés",
                "ordering": ["-last_seen_at", "-confidence_score"],
                "indexes": [
                    models.Index(fields=["country", "sector", "status"], name="outreach_scraped_country_idx"),
                    models.Index(fields=["confidence_score", "last_seen_at"], name="outreach_scraped_score_idx"),
                ],
            },
        ),
    ]
