# Generated by Django 5.2.7 on 2026-06-04 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_scrapedemployerlead_nz'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedemployerlead',
            name='verification_decision',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Décision vérification'),
        ),
        migrations.AddField(
            model_name='scrapedemployerlead',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notes vérification'),
        ),
        migrations.AddField(
            model_name='scrapedemployerlead',
            name='verification_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Score vérification'),
        ),
        migrations.AddField(
            model_name='scrapedemployerlead',
            name='verification_signals',
            field=models.JSONField(blank=True, default=list, verbose_name='Signaux vérification'),
        ),
        migrations.CreateModel(
            name='ScamAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Score risque')),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], db_index=True, default='medium', max_length=20, verbose_name='Niveau risque')),
                ('flags', models.JSONField(blank=True, default=list, verbose_name='Alertes détectées')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recommandation')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name="Date d'analyse")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scam_assessment', to='outreach.scrapedemployerlead', verbose_name='Lead employeur')),
            ],
            options={
                'verbose_name': 'Analyse anti-arnaque',
                'verbose_name_plural': 'Analyses anti-arnaque',
                'ordering': ['-assessed_at', '-risk_score'],
                'indexes': [models.Index(fields=['risk_level', 'risk_score'], name='outreach_scam_risk_idx')],
            },
        ),
    ]
