# Generated by Django 5.2.7 on 2026-06-04 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_scrapedemployerlead_verification_decision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVisaEligibilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Âge')),
                ('country', models.CharField(max_length=120, verbose_name='Pays de résidence')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville')),
                ('profession', models.CharField(max_length=160, verbose_name='Métier principal')),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture / Agroalimentaire'), ('construction', 'Construction / BTP'), ('tech', 'Technologie / IT'), ('sante', 'Santé / Médical'), ('logistique', 'Transport / Logistique'), ('hotellerie', 'Hôtellerie / Restauration'), ('education', 'Éducation / Formation'), ('finance', 'Finance / Comptabilité'), ('industrie', 'Industrie / Manufacture'), ('commerce', 'Commerce / Vente'), ('services', 'Services aux entreprises'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Secteur')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name="Années d'expérience")),
                ('education_level', models.CharField(choices=[('none', 'Aucun diplôme'), ('secondary', 'Secondaire / Bac'), ('vocational', 'Formation professionnelle / CAP / BTS'), ('bachelor', 'Licence / Bachelor'), ('master', 'Master'), ('phd', 'Doctorat')], default='secondary', max_length=20, verbose_name="Niveau d'études")),
                ('certificates', models.TextField(blank=True, verbose_name='Diplômes / certificats')),
                ('french_level', models.CharField(choices=[('none', 'Aucun / débutant'), ('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], default='b1', max_length=10, verbose_name='Niveau français')),
                ('english_level', models.CharField(choices=[('none', 'Aucun / débutant'), ('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], default='none', max_length=10, verbose_name='Niveau anglais')),
                ('has_passport', models.BooleanField(default=False, verbose_name='Passeport disponible')),
                ('has_cv', models.BooleanField(default=False, verbose_name='CV disponible')),
                ('budget', models.CharField(choices=[('low', 'Moins de 300 000 FCFA'), ('medium', '300 000 à 1 500 000 FCFA'), ('good', '1 500 000 à 4 000 000 FCFA'), ('strong', 'Plus de 4 000 000 FCFA')], default='medium', max_length=20, verbose_name='Budget approximatif')),
                ('preferred_countries', models.CharField(default='CA,NZ,AU,EU', help_text='Codes séparés par virgule: CA,NZ,AU,GB,DE,BE,FR,EU', max_length=120, verbose_name='Pays préférés')),
                ('readiness_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score préparation')),
                ('recommended_countries', models.JSONField(blank=True, default=list, verbose_name='Pays recommandés')),
                ('accessible_jobs', models.JSONField(blank=True, default=list, verbose_name='Métiers accessibles')),
                ('missing_documents', models.JSONField(blank=True, default=list, verbose_name='Documents manquants')),
                ('action_plan', models.JSONField(blank=True, default=list, verbose_name="Plan d'action")),
                ('result_summary', models.TextField(blank=True, verbose_name='Résumé résultat')),
                ('raw_result', models.JSONField(blank=True, default=dict, verbose_name='Résultat complet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_visa_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Éligibilité emploi + visa',
                'verbose_name_plural': 'Éligibilités emploi + visa',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='outreach_jobvisa_user_idx'), models.Index(fields=['sector', 'readiness_score'], name='outreach_jobvisa_sector_idx')],
            },
        ),
    ]
