# Generated by Django 5.2.7 on 2026-06-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0005_followuptemplate_joblead_applied_at_and_more'),
        ('profiles', '0006_add_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicjoboffer',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Métier/catégorie cible pour recommander cette offre aux candidats.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_job_offers', to='profiles.category'),
        ),
        migrations.AddField(
            model_name='publicjoboffer',
            name='skills_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules: Python, soudure, Excel...', max_length=300),
        ),
        migrations.AddIndex(
            model_name='publicjoboffer',
            index=models.Index(fields=['category', 'is_active', 'created_at'], name='job_agent_p_categor_29e22f_idx'),
        ),
    ]
