# Generated by Django 5.2.7 on 2026-06-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0006_publicjoboffer_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpack',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='ai_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='ats_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='coach_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='missing_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='applicationpack',
            name='tailored_cv_text',
            field=models.TextField(blank=True),
        ),
    ]
