# Generated by Django 5.2.7 on 2026-06-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0007_applicationpack_ai_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicjoboffer',
            name='url',
            field=models.URLField(max_length=600, unique=True),
        ),
    ]
