# Generated by Django 5.2.7 on 2026-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_agent', '0008_alter_publicjoboffer_url'),
        ('profiles', '0006_add_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicjoboffer',
            name='application_deadline',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='publicjoboffer',
            name='foreign_access_label',
            field=models.CharField(blank=True, help_text='Badge lisible: Accessible étranger, LMIA/EIMT, À vérifier...', max_length=80),
        ),
        migrations.AddField(
            model_name='publicjoboffer',
            name='foreign_access_score',
            field=models.PositiveSmallIntegerField(default=0, help_text="Score 0-100 indiquant si l'offre semble accessible aux candidats étrangers."),
        ),
        migrations.AddField(
            model_name='publicjoboffer',
            name='province',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='publicjoboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='publicjoboffer',
            name='vacancies',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='publicjoboffer',
            name='who_can_apply',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='publicjoboffer',
            index=models.Index(fields=['foreign_access_score', 'is_active', 'created_at'], name='job_agent_p_foreign_52d6d0_idx'),
        ),
    ]
