# Generated by Django 5.2.7 on 2026-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaetude', '0009_alter_studentprofile_budget_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicScholarshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField(max_length=700, unique=True)),
                ('title', models.CharField(max_length=260)),
                ('organization', models.CharField(blank=True, max_length=220)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('study_level', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('postdoc', 'Postdoctorat'), ('short', 'Formation courte'), ('all', 'Tous niveaux'), ('unknown', 'À vérifier')], default='unknown', max_length=20)),
                ('funding_type', models.CharField(choices=[('full', 'Bourse complète'), ('partial', 'Bourse partielle'), ('tuition', 'Frais de scolarité'), ('stipend', 'Allocation'), ('unknown', 'À vérifier')], default='unknown', max_length=20)),
                ('amount', models.CharField(blank=True, max_length=180)),
                ('eligible_countries', models.CharField(blank=True, max_length=260)),
                ('deadline', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('description_text', models.TextField(blank=True)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('verification_label', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='visaetude_p_is_acti_e47240_idx'), models.Index(fields=['country', 'is_active', 'created_at'], name='visaetude_p_country_483515_idx'), models.Index(fields=['study_level', 'is_active', 'created_at'], name='visaetude_p_study_l_3c652f_idx'), models.Index(fields=['funding_type', 'is_active', 'created_at'], name='visaetude_p_funding_7d8a1f_idx'), models.Index(fields=['confidence_score', 'is_active', 'created_at'], name='visaetude_p_confide_d3008b_idx')],
            },
        ),
    ]
